file(
	GLOB
	PROJECT_CONFIGURE_CMAKE
	${PROJECT_SOURCE_DIR}/cmake/*Config.cmake.in
)
foreach(ONE ${PROJECT_FIND_CMAKE})
	configure_file(
		${ONE}
		${CMAKE_BINARY_DIR}/lib/cmake
		@ONLY
	)
endforeach()
configure_file(
	${PROJECT_CONFIGURE_CMAKE}
	${CMAKE_BINARY_DIR}/lib/cmake/${PROJECT_NAME}Config.cmake
	@ONLY
)
install(
	FILES
	${CMAKE_BINARY_DIR}/lib/cmake/${PROJECT_NAME}Config.cmake
	${PROJECT_FIND_CMAKE}
	DESTINATION
	lib/cmake
)